apiVersion: v1
kind: ConfigMap
metadata:
  name: snowplow-kafka-pg-loader-config
  labels:
    app: {{ .Release.Name }}-snowplow-kafka-pg-loader
data:
  config.conf: |

  
  kafka.brokers: pkc-12576z.us-west2.gcp.confluent.cloud:9092,kafka.confluent.svc.cluster.local:9092
  kafka.topic: snowplow_enriched_good
  kafka.security.protocol: SASL_SSL
  kafka.sasl.mechanisms: PLAIN
  kafka.sasl.username: UJXR2AHHSOHL2O4K
  kafka.sasl.password: L4piWdT0pE4t+LiP5xLrkfWxmhePL8jdk0LaSX2N5cSevSBF1EHjr2oygqJX64FC
  postgres.url: jdbc:postgresql://ep-proud-snow-a55l1fw5.us-east-2.aws.neon.tech/igludb?sslmode=require?currentSchema=atomic
  postgres.username: sp_user
  postgres.password: dcKjguD92WeY