apiVersion: v1
kind: ConfigMap
metadata:
  name: snowplow-kafka-pg-loader-config
  labels:
    app: {{ .Release.Name }}-snowplow-kafka-pg-loader
data:
  config.conf: |
    kafka {
      brokers = "kafka.confluent.svc.cluster.local:9092"
      topic = "snowplow_enriched_good"
      consumerGroupId = "kafkaPGLoader"
      producerConf {
        "security.protocol" = "SASL_SSL"
        "sasl.mechanisms" = "PLAIN"
        "sasl.username" = "UJXR2AHHSOHL2O4K"
        "sasl.password" = "L4piWdT0pE4t+LiP5xLrkfWxmhePL8jdk0LaSX2N5cSevSBF1EHjr2oygqJX64FC"
      }
      consumerConf {
        "security.protocol" = "SASL_SSL"
        "sasl.mechanisms" = "PLAIN"
        "sasl.username" = "UJXR2AHHSOHL2O4K"
        "sasl.password" = "L4piWdT0pE4t+LiP5xLrkfWxmhePL8jdk0LaSX2N5cSevSBF1EHjr2oygqJX64FC"
      }
    }

    postgres {
      driver = "org.postgresql.Driver"
      url = "jdbc:postgresql://iglu-postgres.snowplow.svc.cluster.local:5432/igludb?currentSchema=atomic"
      username = "sp_user"
      password = "sp_password"
      groupid = "GroupID"
      numberOfThreads = 1
    }
