replicaCount: 1

image:
  repository: myrepo/websocket
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8000

ingress:
  enabled: true
  annotations: {}
  hosts:
    - host: websocket.local
      paths:
        - path: /
          pathType: Prefix
          port: 8000
  tls: []
