replicaCount: 1

image:
  repository: socrates12345/websocket
  tag: "1.0.2"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8000

ingress:
  enabled: true
  annotations: {}
  hosts:
    - paths:
        - path: /
          pathType: Prefix

resources: {}
