apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: snowplow-platform
  namespace: default
spec:
  project: default

  source:
    repoURL: 'https://github.com/socrates-kubefirst/argo-gitops.git'
    targetRevision: HEAD
    path: snow-plow
    directory:
      recurse: true
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true

