apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web
  annotations:
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
spec:
  rules:
    {{- range .Values.ingress.hosts }}
    -  http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: web
                port:
                  number: {{ $.Values.service.port }}
          {{- end }}
    {{- end }}
