apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: events-processor
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/socrates-kubefirst/argo-gitops.git'
    targetRevision: HEAD
    path: charts/events-processor
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
