apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: snowplow-kafka-pg-loader
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/socrates-kubefirst/argo-gitops.git'
    targetRevision: HEAD
    path: charts/snowplow-kafka-pg-loader
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: snowplow
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true

