versionNumber: 7.6.0
namespace: confluent
zookeeper:
  ports:
    clientPort: 2181
  environment:
    ZOOKEEPER_CLIENT_PORT: 2181
    ZOOKEEPER_TICK_TIME: 2000

kafka:
  ports:
    - containerPort: 9092
      hostPort: 9092
    - containerPort: 9101
      hostPort: 9101
  environment:
    KAFKA_BROKER_ID: 1
    KAFKA_ZOOKEEPER_CONNECT: 'zookeeper.confluent.svc.cluster.local:2181'
    KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
    KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka.confluent.svc.cluster.local:29092,PLAINTEXT_HOST://localhost:9092'
    KAFKA_METRIC_REPORTERS: 'io.confluent.metrics.reporter.ConfluentMetricsReporter'
    KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 1
    KAFKA_CONFLUENT_BALANCER_TOPIC_REPLICATION_FACTOR: 1
    KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
    KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    KAFKA_JMX_PORT: 9101
    KAFKA_JMX_HOSTNAME: '{{ .Release.Name }}-kafka.{{ .Values.namespace }}.svc.cluster.local'
    CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: 'kafka.confluent.svc.cluster.local:29092'
    CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS: 1
    CONFLUENT_METRICS_ENABLE: 'true'
    CONFLUENT_SUPPORT_CUSTOMER_ID: 'anonymous'
  initContainers:
    enabled: true
    topics:
      - name: snowplow_raw_good
        partitions: 3
        replicationFactor: 1
      - name: snowplow_enriched_good
        partitions: 3
        replicationFactor: 1
      - name: snowplow_enriched_bad
        partitions: 3
        replicationFactor: 1

controlcenter:
  ports:
    - containerPort: 9021
      hostPort: 9021
  environment:
    CONTROL_CENTER_BOOTSTRAP_SERVERS: 'kafka.confluent.svc.cluster.local:29092'
    CONTROL_CENTER_REPLICATION_FACTOR: 1
    CONTROL_CENTER_INTERNAL_TOPICS_PARTITIONS: 1
    CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_PARTITIONS: 1
    CONFLUENT_METRICS_TOPIC_REPLICATION: 1
    PORT: 9021
  service:
    type: LoadBalancer
